# Generated by Django 2.1.1 on 2018-09-23 15:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('art', cloudinary.models.CloudinaryField(max_length=255, verbose_name='art')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('galleryimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='galleryimage')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryGroup'),
        ),
    ]
