# Generated by Django 2.1.1 on 2018-10-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='gcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcategory', to='gallery.Gallery_Category'),
        ),
    ]
