# Generated by Django 2.1.1 on 2018-10-01 17:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181001_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
