# Generated by Django 2.1.1 on 2018-09-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180924_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productss', to='gallery.Category'),
        ),
    ]
