# Generated by Django 2.1.1 on 2018-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
