# Generated by Django 2.1.1 on 2018-09-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_artwork_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'artwork Translation',
                'db_table': 'gallery_artwork_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.AddField(
            model_name='artworktranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gallery.Artwork'),
        ),
        migrations.AlterUniqueTogether(
            name='artworktranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
