# Generated by Django 2.1.1 on 2018-09-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180924_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworktranslation',
            name='slug',
        ),
    ]
