# Generated by Django 2.1.1 on 2018-09-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_artworktranslation_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Gallery_Category',
        ),
        migrations.RenameModel(
            old_name='CategoryTranslation',
            new_name='Gallery_CategoryTranslation',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.AlterModelTable(
            name='gallery_categorytranslation',
            table='gallery_gallery_category_translation',
        ),
    ]
