# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20150428_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art',
            field=models.ImageField(upload_to='art'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerygroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
