# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20180912_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
