# Generated by Django 2.1.1 on 2018-09-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20180925_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productss', to='gallery.Gallery_Category'),
        ),
    ]
