# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_artwork_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='timestamp',
        ),
    ]
