# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_artwork_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
