# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20180912_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
