# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-12 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_artwork_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='url',
            new_name='link',
        ),
    ]
