# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20180912_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerygroup',
            name='galleryimage',
            field=models.ImageField(default=1, upload_to='galleryimage'),
            preserve_default=False,
        ),
    ]
