# Generated by Django 2.0 on 2018-09-15 07:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_gallerygroup_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='art'),
        ),
        migrations.AlterField(
            model_name='gallerygroup',
            name='galleryimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='galleryimage'),
        ),
    ]
