# Generated by Django 2.1.1 on 2018-09-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='name',
            new_name='title',
        ),
    ]
