# Generated by Django 2.1.1 on 2018-09-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
